apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h8gkhqy99-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:8a29879aca5f6df872503ab2cc495fd58197096b@sha256:64d58b7c5b615af32b3ac9bfb74dbe4c775898db0e2f2497368b94377af7b05d
          name: container-image
